/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.GroomingAdmin;

import Business.EcoSystem;
import Employee.Employee;
import Enterprise.Enterprise;
import Models.Organization.Organization;
import Network.Network;
import Roles.StylistRole;
import Roles.DesignerRole;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author vikashsingh
 */
public class manageBusinessUserPanel extends javax.swing.JPanel {

    /**
     * Creates new form networkPanel
     */
    EcoSystem system;
    Employee emp;
    Enterprise ent;
    Network net;
    Organization org;
    public manageBusinessUserPanel(EcoSystem system,Employee emp) {
        this.emp=emp;
        this.system = system;
        initComponents();
        adminPanelCard.setBackground(new Color(0,0,0,90));
        populateCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adminPanelCard = new javax.swing.JPanel();
        lblOrganisation = new javax.swing.JLabel();
        btnAddUser = new javax.swing.JButton();
        nameLabel = new javax.swing.JLabel();
        dropdownEnterprise = new javax.swing.JComboBox<>();
        lblusrName = new javax.swing.JLabel();
        lblPwd = new javax.swing.JLabel();
        txtAdminPwd = new javax.swing.JTextField();
        txtAdminName = new javax.swing.JTextField();
        txtAdminUsrName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        dropdownNetwork = new javax.swing.JComboBox<>();
        adminBackgroundImg = new javax.swing.JLabel();

        setSize(new java.awt.Dimension(977, 630));
        setLayout(null);

        lblOrganisation.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblOrganisation.setForeground(new java.awt.Color(255, 255, 255));
        lblOrganisation.setText("Organisation Name");

        btnAddUser.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnAddUser.setText("Add User");
        btnAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddUserActionPerformed(evt);
            }
        });

        nameLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(255, 255, 255));
        nameLabel.setText("Name");

        dropdownEnterprise.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N

        lblusrName.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblusrName.setForeground(new java.awt.Color(255, 255, 255));
        lblusrName.setText("User Name");

        lblPwd.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblPwd.setForeground(new java.awt.Color(255, 255, 255));
        lblPwd.setText("Password");

        txtAdminPwd.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N

        txtAdminName.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        txtAdminName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAdminNameActionPerformed(evt);
            }
        });

        txtAdminUsrName.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Enterprise Name");

        dropdownNetwork.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N

        javax.swing.GroupLayout adminPanelCardLayout = new javax.swing.GroupLayout(adminPanelCard);
        adminPanelCard.setLayout(adminPanelCardLayout);
        adminPanelCardLayout.setHorizontalGroup(
            adminPanelCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminPanelCardLayout.createSequentialGroup()
                .addGroup(adminPanelCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adminPanelCardLayout.createSequentialGroup()
                        .addGap(447, 447, 447)
                        .addComponent(btnAddUser, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(adminPanelCardLayout.createSequentialGroup()
                        .addGap(315, 315, 315)
                        .addGroup(adminPanelCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblOrganisation, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblusrName, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPwd, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(78, 78, 78)
                        .addGroup(adminPanelCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dropdownNetwork, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(adminPanelCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtAdminPwd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(dropdownEnterprise, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtAdminName)
                                .addComponent(txtAdminUsrName, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(323, Short.MAX_VALUE))
        );
        adminPanelCardLayout.setVerticalGroup(
            adminPanelCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminPanelCardLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(adminPanelCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dropdownNetwork, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(36, 36, 36)
                .addGroup(adminPanelCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOrganisation)
                    .addComponent(dropdownEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(adminPanelCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(txtAdminName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(adminPanelCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblusrName)
                    .addComponent(txtAdminUsrName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(adminPanelCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPwd)
                    .addComponent(txtAdminPwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76)
                .addComponent(btnAddUser, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(122, Short.MAX_VALUE))
        );

        add(adminPanelCard);
        adminPanelCard.setBounds(0, 0, 1090, 630);

        adminBackgroundImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/desingerBg.jpeg"))); // NOI18N
        add(adminBackgroundImg);
        adminBackgroundImg.setBounds(0, 0, 1090, 630);
    }// </editor-fold>//GEN-END:initComponents

    private void txtAdminNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAdminNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAdminNameActionPerformed

    private void btnAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddUserActionPerformed
        // TODO add your handling code here:
        String userName = txtAdminUsrName.getText();
        String password = txtAdminPwd.getText();
            if ("".equals(userName)) {
                JOptionPane.showMessageDialog(null, "Please enter username");
            } else if (!system.checkIfUserIsUnique(system,userName)) {
                JOptionPane.showMessageDialog(null, "Please enter unique username");
            } else if ("".equals(password)) {
                JOptionPane.showMessageDialog(null, "Please enter password");
            } else {
            for(Organization org:ent.getOrganizationList().getOrganizationList()){
                if(org.getName().equals(dropdownEnterprise.getSelectedItem()))
                    this.org=org;
            }
            if(this.org.getType()==Organization.Type.Stylist)
            {
                system.getEmployeedirectory().createEmployee(txtAdminName.getText(),  userName, password, new StylistRole(),net.getName(), this.org.getId());
                this.org.getEmployees().createEmployee(txtAdminName.getText(),userName, password, new StylistRole(),net.getName(), this.org.getId());
            }
            else {
             system.getEmployeedirectory().createEmployee(txtAdminName.getText(),  userName, password, new DesignerRole(),net.getName(), this.org.getId());
             this.org.getEmployees().createEmployee(txtAdminName.getText(),  userName, password, new DesignerRole(),net.getName(), this.org.getId());
            }
            JOptionPane.showMessageDialog(null, "User Account Created");
            txtAdminUsrName.setText("");
            txtAdminPwd.setText("");
            txtAdminName.setText("");
        }
    }//GEN-LAST:event_btnAddUserActionPerformed
    private void populateCombo(){
        dropdownNetwork.removeAllItems();
        dropdownEnterprise.removeAllItems();
        for (Network network :system.getNetworkList()){
            net=network;
            if(emp.getNetworkname().equals(network.getName())){
            for(Enterprise ent: network.getEnterpriseDirectory().getEnterpriseList()){
                if (ent.getEnterpriseType()==Enterprise.EnterpriseType.Grooming){
                    dropdownNetwork.addItem(ent.getEnterpriseName());  
                    this.ent=ent;
                    for(Organization org:ent.getOrganizationList().getOrganizationList()){
                        dropdownEnterprise.addItem(org.getName());
                    }
                }
            }
            }
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adminBackgroundImg;
    private javax.swing.JPanel adminPanelCard;
    private javax.swing.JButton btnAddUser;
    private javax.swing.JComboBox<String> dropdownEnterprise;
    private javax.swing.JComboBox<String> dropdownNetwork;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblOrganisation;
    private javax.swing.JLabel lblPwd;
    private javax.swing.JLabel lblusrName;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField txtAdminName;
    private javax.swing.JTextField txtAdminPwd;
    private javax.swing.JTextField txtAdminUsrName;
    // End of variables declaration//GEN-END:variables
}
