/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.SingleUser;

import Business.EcoSystem;
import Employee.Employee;
import User.SingleUser;
import ui.User.*;
import ui.SystemAdmin.*;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author athipathi
 */
public class findMatchPanel extends javax.swing.JPanel {

    /**
     * Creates new form networkPanel
     */
    EcoSystem system;
    SingleUser user;
    public findMatchPanel(EcoSystem system,SingleUser user) {
        this.system=system;
        this.user=user;
        initComponents();
        adminPanelCard.setBackground(new Color(0,0,0,90));
        populateTable();
    }
    
    public void populateTable(){
         DefaultTableModel model = (DefaultTableModel) matchTable.getModel();
          model.setRowCount(0);
         for (SingleUser singleUser : system.getSingleUserlist().getSingleUserList()) {
             if(!singleUser.getUserName().equals(user.getUserName())){
                 if(singleUser.getGender().equals(user.getPreferredGender())&& singleUser.getHobbies().equals(user.getPreferredHobbies())){
                            Object row[] = new Object[7];
                            row[0] = singleUser.getImage();
                            row[1] = singleUser.getName();
                            row[2] = singleUser.getAge();
                            row[3] = singleUser.getHobbies();
                            row[4] = singleUser.getZodiacSign();
                            row[5] = singleUser.getUserName();
                            row[6] = singleUser;
                            ((DefaultTableModel) matchTable.getModel()).addRow(row);
                 }
                 else{
                     JOptionPane.showMessageDialog(null, "No Match Found According to Your Preferences :( !!");
                 }
             }
         }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adminPanelCard = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        matchTable = new javax.swing.JTable();
        adminBackgroundImg = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(977, 630));
        setSize(new java.awt.Dimension(1090, 630));
        setLayout(null);

        adminPanelCard.setFocusable(false);
        adminPanelCard.setOpaque(false);

        matchTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Image", "Name", "Age", "Hobbies", "Zodiac", "UserName", "User"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, true, true, true, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        matchTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                matchTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(matchTable);
        if (matchTable.getColumnModel().getColumnCount() > 0) {
            matchTable.getColumnModel().getColumn(5).setMinWidth(0);
            matchTable.getColumnModel().getColumn(5).setPreferredWidth(0);
            matchTable.getColumnModel().getColumn(5).setMaxWidth(0);
            matchTable.getColumnModel().getColumn(6).setMinWidth(0);
            matchTable.getColumnModel().getColumn(6).setPreferredWidth(0);
            matchTable.getColumnModel().getColumn(6).setMaxWidth(0);
        }

        javax.swing.GroupLayout adminPanelCardLayout = new javax.swing.GroupLayout(adminPanelCard);
        adminPanelCard.setLayout(adminPanelCardLayout);
        adminPanelCardLayout.setHorizontalGroup(
            adminPanelCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adminPanelCardLayout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 807, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
        );
        adminPanelCardLayout.setVerticalGroup(
            adminPanelCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminPanelCardLayout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        add(adminPanelCard);
        adminPanelCard.setBounds(0, 0, 970, 640);

        adminBackgroundImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/wedding-Background_Image.jpeg"))); // NOI18N
        adminBackgroundImg.setPreferredSize(new java.awt.Dimension(977, 630));
        add(adminBackgroundImg);
        adminBackgroundImg.setBounds(0, 0, 1090, 630);
    }// </editor-fold>//GEN-END:initComponents

    private void matchTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_matchTableMouseClicked
        // TODO add your handling code here:

        SingleUser singleUser= (SingleUser) matchTable.getValueAt(matchTable.getSelectedRow(), 6);
        JOptionPane.showMessageDialog(null, "Do you Want to send a request to "+singleUser.getUserName());
    }//GEN-LAST:event_matchTableMouseClicked
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adminBackgroundImg;
    private javax.swing.JPanel adminPanelCard;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable matchTable;
    // End of variables declaration//GEN-END:variables
}
