/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.BakerPanel;

import Business.EcoSystem;
import Employee.Employee;
import Enterprise.Enterprise;
import Models.Organization.Organization;
import Network.Network;
import ui.SystemAdmin.*;
import java.awt.Color;

/**
 *
 * @author vikashsingh
 */
public class bakerItemsPanel extends javax.swing.JPanel {

    /**
     * Creates new form networkPanel
     */
    
   EcoSystem system;
   Organization org;
   Employee employee;
    
    public bakerItemsPanel(EcoSystem system, Employee employee) {
        initComponents();
        this.system = system;
        this.employee = employee;
        getOrganization(employee.getOrgId(), system);
        adminPanelCard.setBackground(new Color(0,0,0,90));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adminPanelCard = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ItemsTable = new javax.swing.JTable();
        btnCreateCake = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        ItemName = new javax.swing.JLabel();
        cakeName = new javax.swing.JTextField();
        FlavourLabel = new javax.swing.JLabel();
        flavourValue = new javax.swing.JTextField();
        ServesLabel = new javax.swing.JLabel();
        serveValue = new javax.swing.JTextField();
        priceLabel = new javax.swing.JLabel();
        PriceValue = new javax.swing.JTextField();
        ImageLabel = new javax.swing.JLabel();
        btnUploadImg = new javax.swing.JButton();
        cakeImg = new javax.swing.JLabel();
        adminBackgroundImg = new javax.swing.JLabel();

        setSize(new java.awt.Dimension(977, 630));
        setLayout(null);

        ItemsTable.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        ItemsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Item", "Flavour", "Server", "Price", "Image"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(ItemsTable);

        btnCreateCake.setText("Add Item");
        btnCreateCake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateCakeActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");

        ItemName.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        ItemName.setForeground(new java.awt.Color(255, 255, 255));
        ItemName.setText("Item Name");

        cakeName.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N

        FlavourLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        FlavourLabel.setForeground(new java.awt.Color(255, 255, 255));
        FlavourLabel.setText("Flavour");

        flavourValue.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N

        ServesLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        ServesLabel.setForeground(new java.awt.Color(255, 255, 255));
        ServesLabel.setText("Serves");

        serveValue.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N

        priceLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        priceLabel.setForeground(new java.awt.Color(255, 255, 255));
        priceLabel.setText("Price");

        PriceValue.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N

        ImageLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        ImageLabel.setForeground(new java.awt.Color(255, 255, 255));
        ImageLabel.setText("Image");

        btnUploadImg.setText("Upload Image");

        javax.swing.GroupLayout adminPanelCardLayout = new javax.swing.GroupLayout(adminPanelCard);
        adminPanelCard.setLayout(adminPanelCardLayout);
        adminPanelCardLayout.setHorizontalGroup(
            adminPanelCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminPanelCardLayout.createSequentialGroup()
                .addGroup(adminPanelCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adminPanelCardLayout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(adminPanelCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(adminPanelCardLayout.createSequentialGroup()
                                .addGroup(adminPanelCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(adminPanelCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(adminPanelCardLayout.createSequentialGroup()
                                            .addComponent(FlavourLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(flavourValue, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(adminPanelCardLayout.createSequentialGroup()
                                            .addComponent(ItemName, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(cakeName, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(adminPanelCardLayout.createSequentialGroup()
                                            .addComponent(ServesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(serveValue, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(adminPanelCardLayout.createSequentialGroup()
                                            .addComponent(priceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(PriceValue, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(ImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(255, 255, 255)
                                .addComponent(cakeImg, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(adminPanelCardLayout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addGroup(adminPanelCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnUploadImg)
                            .addGroup(adminPanelCardLayout.createSequentialGroup()
                                .addComponent(btnCreateCake, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(185, Short.MAX_VALUE))
        );
        adminPanelCardLayout.setVerticalGroup(
            adminPanelCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminPanelCardLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(adminPanelCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adminPanelCardLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(cakeImg, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                        .addGroup(adminPanelCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCreateCake, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(69, 69, 69))
                    .addGroup(adminPanelCardLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(adminPanelCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ItemName)
                            .addComponent(cakeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(adminPanelCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FlavourLabel)
                            .addComponent(flavourValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(adminPanelCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ServesLabel)
                            .addComponent(serveValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(adminPanelCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(priceLabel)
                            .addComponent(PriceValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(adminPanelCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ImageLabel)
                            .addComponent(btnUploadImg))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        add(adminPanelCard);
        adminPanelCard.setBounds(0, 0, 1090, 630);

        adminBackgroundImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/weddingcake.jpeg"))); // NOI18N
        add(adminBackgroundImg);
        adminBackgroundImg.setBounds(0, 0, 1090, 630);
    }// </editor-fold>//GEN-END:initComponents

    
    private Organization getOrganization (long orgId, EcoSystem system){
//       Network network = system.retriveNetwork(employee.getNetworkname());
//       Organization org = null;
//       for(int i=0;i< network.getEnterpriseDirectory().getEnterpriseList().size(); i++){
//           Enterprise enterprise = network.getEnterpriseDirectory().getEnterpriseList().get(i);
//           for (Organization organization : enterprise.getOrganizationList().getOrganizationList()) {
//               if(organization.getId() == orgId){
//                   org=organization;
//
//               }
//           }
//       }
       return org;
    }
    
    private void btnCreateCakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateCakeActionPerformed
        String name = cakeName.getText().trim();
        String flavour = flavourValue.getText().trim();
        String serves = serveValue.getText().trim();
        String price = PriceValue.getText().trim();
        System.out.println(name +" "+ flavour+  " "+serves + " "+ price);
        System.out.println(employee.getOrgId());
        Organization organization = getOrganization(employee.getOrgId(), this.system);
    }//GEN-LAST:event_btnCreateCakeActionPerformed

    
    private void populateTable(){
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FlavourLabel;
    private javax.swing.JLabel ImageLabel;
    private javax.swing.JLabel ItemName;
    private javax.swing.JTable ItemsTable;
    private javax.swing.JTextField PriceValue;
    private javax.swing.JLabel ServesLabel;
    private javax.swing.JLabel adminBackgroundImg;
    private javax.swing.JPanel adminPanelCard;
    private javax.swing.JButton btnCreateCake;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUploadImg;
    private javax.swing.JLabel cakeImg;
    private javax.swing.JTextField cakeName;
    private javax.swing.JTextField flavourValue;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JTextField serveValue;
    // End of variables declaration//GEN-END:variables
}
