/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.FinanceAdmin;

import Business.EcoSystem;
import Employee.Employee;
/**
 *
 * @author vikashsingh
 */
public class mainPanelFinanceAdmin extends javax.swing.JPanel {
    

    /**
     * Creates new form mainPanelSysadmin
     */
    
    EcoSystem system;
    Employee employeeAccount;
    displayEmployee employee ;
    organisationPanel organisation; 
    manageBusinessUserPanel manageUser;
    public mainPanelFinanceAdmin() {
        initComponents();
       
    }
    
    public mainPanelFinanceAdmin(EcoSystem system,Employee emp) {
        initComponents();
        this.system = system;
        this.employeeAccount=emp;
        splitPane.setRightComponent(organisation);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        sysAdminMenuPanel = new javax.swing.JPanel();
        sysAdminProfileImg = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnOrganisation = new javax.swing.JButton();
        btnUsers = new javax.swing.JButton();
        btnDisplay = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(1210, 630));
        setPreferredSize(new java.awt.Dimension(1210, 630));
        setSize(new java.awt.Dimension(1210, 630));

        sysAdminProfileImg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sysAdminProfileImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/adminGirl.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Welcome FinanceAdmin!");

        btnOrganisation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/manageIcon.png"))); // NOI18N
        btnOrganisation.setText("       Manage Organisation");
        btnOrganisation.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnOrganisation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrganisationActionPerformed(evt);
            }
        });

        btnUsers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/admins.png"))); // NOI18N
        btnUsers.setText("       Manage Users");
        btnUsers.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsersActionPerformed(evt);
            }
        });

        btnDisplay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/admins.png"))); // NOI18N
        btnDisplay.setText("       Display Users");
        btnDisplay.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sysAdminMenuPanelLayout = new javax.swing.GroupLayout(sysAdminMenuPanel);
        sysAdminMenuPanel.setLayout(sysAdminMenuPanelLayout);
        sysAdminMenuPanelLayout.setHorizontalGroup(
            sysAdminMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sysAdminMenuPanelLayout.createSequentialGroup()
                .addGroup(sysAdminMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sysAdminMenuPanelLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(sysAdminProfileImg))
                    .addGroup(sysAdminMenuPanelLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(sysAdminMenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sysAdminMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUsers, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnOrganisation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        sysAdminMenuPanelLayout.setVerticalGroup(
            sysAdminMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sysAdminMenuPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(sysAdminProfileImg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnOrganisation)
                .addGap(27, 27, 27)
                .addComponent(btnUsers)
                .addGap(27, 27, 27)
                .addComponent(btnDisplay)
                .addContainerGap(229, Short.MAX_VALUE))
        );

        splitPane.setLeftComponent(sysAdminMenuPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1210, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(splitPane, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnOrganisationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrganisationActionPerformed
        // TODO add your handling code here:
//        organisation = new organisationPanel(system,employeeAccount);
        splitPane.setRightComponent(organisation);
        
    }//GEN-LAST:event_btnOrganisationActionPerformed

    private void btnUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsersActionPerformed
        // TODO add your handling code here:
//        manageUser=new manageBusinessUserPanel(system,employeeAccount);
        splitPane.setRightComponent(manageUser);
    }//GEN-LAST:event_btnUsersActionPerformed

    private void btnDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplayActionPerformed
        // TODO add your handling code here:
//        employee = new displayEmployee(system,employeeAccount);
        splitPane.setRightComponent(employee);
    }//GEN-LAST:event_btnDisplayActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDisplay;
    private javax.swing.JButton btnOrganisation;
    private javax.swing.JButton btnUsers;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JPanel sysAdminMenuPanel;
    private javax.swing.JLabel sysAdminProfileImg;
    // End of variables declaration//GEN-END:variables
}
