/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.SystemAdmin;

import Business.EcoSystem;
import DB4OUtil.DB4OUtil;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author athipathi
 */
public class mainPanelSysadmin extends javax.swing.JPanel {

    /**
     * Creates new form mainPanelSysadmin
     */
  
   networkPanel network;
   enterprisePanel enterprise;
   manageAdminPanel manageAdmin;
   displayAdminsPanel displayPanel;
   EcoSystem system;
    public mainPanelSysadmin(EcoSystem system) {
        initComponents();
        this.system=system;
        network = new networkPanel(system);
        splitPane.setRightComponent(network);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        sysAdminMenuPanel = new javax.swing.JPanel();
        sysAdminProfileImg = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnNetwork = new javax.swing.JButton();
        btnEnterprise = new javax.swing.JButton();
        btnAdmins = new javax.swing.JButton();
        btnViewAdmins = new javax.swing.JButton();
        btnViewAdmins1 = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(1210, 630));
        setPreferredSize(new java.awt.Dimension(1210, 630));
        setSize(new java.awt.Dimension(1210, 630));

        sysAdminProfileImg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sysAdminProfileImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/adminGirl.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Welcome SysAdmin!");

        btnNetwork.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/manageIcon.png"))); // NOI18N
        btnNetwork.setText("       Manage Network");
        btnNetwork.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnNetwork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNetworkActionPerformed(evt);
            }
        });

        btnEnterprise.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/manageIcon.png"))); // NOI18N
        btnEnterprise.setText("       Manage Enterprises");
        btnEnterprise.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnEnterprise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnterpriseActionPerformed(evt);
            }
        });

        btnAdmins.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/admins.png"))); // NOI18N
        btnAdmins.setText("       Manage Admins");
        btnAdmins.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAdmins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminsActionPerformed(evt);
            }
        });

        btnViewAdmins.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/admins.png"))); // NOI18N
        btnViewAdmins.setText("       View Admins");
        btnViewAdmins.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnViewAdmins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAdminsActionPerformed(evt);
            }
        });

        btnViewAdmins1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/manageIcon.png"))); // NOI18N
        btnViewAdmins1.setText("       Visualize Data");
        btnViewAdmins1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnViewAdmins1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAdmins1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sysAdminMenuPanelLayout = new javax.swing.GroupLayout(sysAdminMenuPanel);
        sysAdminMenuPanel.setLayout(sysAdminMenuPanelLayout);
        sysAdminMenuPanelLayout.setHorizontalGroup(
            sysAdminMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sysAdminMenuPanelLayout.createSequentialGroup()
                .addGroup(sysAdminMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sysAdminMenuPanelLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(sysAdminProfileImg))
                    .addGroup(sysAdminMenuPanelLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(sysAdminMenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sysAdminMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEnterprise, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNetwork, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAdmins, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViewAdmins, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViewAdmins1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        sysAdminMenuPanelLayout.setVerticalGroup(
            sysAdminMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sysAdminMenuPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(sysAdminProfileImg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnNetwork)
                .addGap(27, 27, 27)
                .addComponent(btnEnterprise)
                .addGap(27, 27, 27)
                .addComponent(btnAdmins)
                .addGap(26, 26, 26)
                .addComponent(btnViewAdmins)
                .addGap(26, 26, 26)
                .addComponent(btnViewAdmins1)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        splitPane.setLeftComponent(sysAdminMenuPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1210, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(splitPane, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNetworkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNetworkActionPerformed
        // TODO add your handling code here:
        network = new networkPanel(system);
        splitPane.setRightComponent(network);
        
    }//GEN-LAST:event_btnNetworkActionPerformed

    private void btnEnterpriseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterpriseActionPerformed
        // TODO add your handling code here:
        enterprise = new enterprisePanel(system);
        splitPane.setRightComponent(enterprise);
    }//GEN-LAST:event_btnEnterpriseActionPerformed

    private void btnAdminsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminsActionPerformed
        // TODO add your handling code here:
        manageAdmin=new manageAdminPanel(system);
        splitPane.setRightComponent(manageAdmin);
    }//GEN-LAST:event_btnAdminsActionPerformed

    private void btnViewAdminsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAdminsActionPerformed
        // TODO add your handling code here:
       displayPanel= new displayAdminsPanel(system);
        splitPane.setRightComponent(displayPanel);
    }//GEN-LAST:event_btnViewAdminsActionPerformed

    private void btnViewAdmins1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAdmins1ActionPerformed
        // TODO add your handling code here:
        drawchart();
    }//GEN-LAST:event_btnViewAdmins1ActionPerformed
     private void drawchart(){
        DefaultPieDataset pieDataset= new DefaultPieDataset();
        pieDataset.setValue("One",1);
        pieDataset.setValue("Two",2);
        pieDataset.setValue("Three",3);
        pieDataset.setValue("Four",1);
        
        JFreeChart chart=ChartFactory.createPieChart("Organizations", pieDataset);
        PiePlot p=(PiePlot)chart.getPlot();
        ChartPanel chartPanel= new ChartPanel(chart);
      
        ChartFrame frame= new ChartFrame("Organizations",chart);
           frame.setVisible(true);
           frame.setSize(450,500);
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdmins;
    private javax.swing.JButton btnEnterprise;
    private javax.swing.JButton btnNetwork;
    private javax.swing.JButton btnViewAdmins;
    private javax.swing.JButton btnViewAdmins1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JPanel sysAdminMenuPanel;
    private javax.swing.JLabel sysAdminProfileImg;
    // End of variables declaration//GEN-END:variables
}
