/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.SystemAdmin;

import Business.EcoSystem;
import DB4OUtil.DB4OUtil;
import Employee.Employee;
import Enterprise.Enterprise;
import Network.Network;
import Roles.*;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author athipathi
 */
public class manageAdminPanel extends javax.swing.JPanel {

    /**
     * Creates new form networkPanel
     */
    EcoSystem system;
    Network network;
    public manageAdminPanel(EcoSystem system) {
        initComponents();
        this.system=system;
        adminPanelCard.setBackground(new Color(0,0,0,90));
        populateNetworkComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adminPanelCard = new javax.swing.JPanel();
        lblEnterprise = new javax.swing.JLabel();
        btnAddenterpriseAdmin = new javax.swing.JButton();
        nameLabel = new javax.swing.JLabel();
        dropdownEnterprise = new javax.swing.JComboBox();
        lblusrName = new javax.swing.JLabel();
        lblPwd = new javax.swing.JLabel();
        txtAdminPwd = new javax.swing.JTextField();
        txtAdminName = new javax.swing.JTextField();
        txtAdminUsrName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        dropdownNetwork = new javax.swing.JComboBox();
        adminBackgroundImg = new javax.swing.JLabel();

        setSize(new java.awt.Dimension(977, 630));
        setLayout(null);

        lblEnterprise.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblEnterprise.setForeground(new java.awt.Color(255, 255, 255));
        lblEnterprise.setText("Enterprise Name");

        btnAddenterpriseAdmin.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnAddenterpriseAdmin.setText("Add Enterprise Admin");
        btnAddenterpriseAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddenterpriseAdminActionPerformed(evt);
            }
        });

        nameLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(255, 255, 255));
        nameLabel.setText("Name");

        dropdownEnterprise.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        dropdownEnterprise.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblusrName.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblusrName.setForeground(new java.awt.Color(255, 255, 255));
        lblusrName.setText("User Name");

        lblPwd.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblPwd.setForeground(new java.awt.Color(255, 255, 255));
        lblPwd.setText("Password");

        txtAdminPwd.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N

        txtAdminName.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        txtAdminName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAdminNameActionPerformed(evt);
            }
        });

        txtAdminUsrName.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Network Name");

        dropdownNetwork.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        dropdownNetwork.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        dropdownNetwork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropdownNetworkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout adminPanelCardLayout = new javax.swing.GroupLayout(adminPanelCard);
        adminPanelCard.setLayout(adminPanelCardLayout);
        adminPanelCardLayout.setHorizontalGroup(
            adminPanelCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminPanelCardLayout.createSequentialGroup()
                .addGroup(adminPanelCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adminPanelCardLayout.createSequentialGroup()
                        .addGap(447, 447, 447)
                        .addComponent(btnAddenterpriseAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(adminPanelCardLayout.createSequentialGroup()
                        .addGap(315, 315, 315)
                        .addGroup(adminPanelCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblusrName, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPwd, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(78, 78, 78)
                        .addGroup(adminPanelCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dropdownNetwork, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(adminPanelCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtAdminPwd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(dropdownEnterprise, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtAdminName)
                                .addComponent(txtAdminUsrName, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(323, Short.MAX_VALUE))
        );
        adminPanelCardLayout.setVerticalGroup(
            adminPanelCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminPanelCardLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(adminPanelCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dropdownNetwork, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(36, 36, 36)
                .addGroup(adminPanelCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEnterprise)
                    .addComponent(dropdownEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(adminPanelCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(txtAdminName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(adminPanelCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblusrName)
                    .addComponent(txtAdminUsrName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(adminPanelCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPwd)
                    .addComponent(txtAdminPwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76)
                .addComponent(btnAddenterpriseAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(122, Short.MAX_VALUE))
        );

        add(adminPanelCard);
        adminPanelCard.setBounds(0, 0, 1090, 630);

        adminBackgroundImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/adminBg.jpeg"))); // NOI18N
        adminBackgroundImg.setPreferredSize(new java.awt.Dimension(977, 630));
        add(adminBackgroundImg);
        adminBackgroundImg.setBounds(0, 0, 1090, 630);
    }// </editor-fold>//GEN-END:initComponents

      private void populateNetworkComboBox() {
        dropdownNetwork.removeAllItems();
        for (Network network : system.getNetworkList()) {
            dropdownNetwork.addItem(network);
        }
    }

    private void populateEnterpriseComboBox(Network network) {
        dropdownEnterprise.removeAllItems();
        for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
            dropdownEnterprise.addItem(enterprise.getEnterpriseName());
        }
    }
    private void txtAdminNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAdminNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAdminNameActionPerformed

    private void dropdownNetworkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropdownNetworkActionPerformed
        // TODO add your handling code here:
         network = (Network) dropdownNetwork.getSelectedItem();
        if (network != null) {
            populateEnterpriseComboBox(network);
        }
    }//GEN-LAST:event_dropdownNetworkActionPerformed

    private void btnAddenterpriseAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddenterpriseAdminActionPerformed
        // TODO add your handling code here:
        Enterprise enterprise =  network.retriveEnterprise(dropdownEnterprise.getSelectedItem().toString());
        String username = txtAdminUsrName.getText();
        String password = String.valueOf(txtAdminPwd.getText());
        String name = txtAdminName.getText();
        if (username.isEmpty() || password.isEmpty() || name.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter all fields", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else {
            if (system.checkIfUserIsUnique(system,username)) {
                Employee employee;
                if(enterprise.getEnterpriseType()==Enterprise.EnterpriseType.EventDecor){
                employee = system.getEmployeedirectory().createEmployee(name,username,password,new DecorAdminRole());
                }else if(enterprise.getEnterpriseType()==Enterprise.EnterpriseType.FoodManagement){
                employee = system.getEmployeedirectory().createEmployee(name,username,password,new FoodAdminRole());
                }
                if(enterprise.getEnterpriseType()==Enterprise.EnterpriseType.Grooming){
                employee = system.getEmployeedirectory().createEmployee(name,username,password,new GroomingAdminRole());
                }
                if(enterprise.getEnterpriseType()==Enterprise.EnterpriseType.Finance){
                employee = system.getEmployeedirectory().createEmployee(name,username,password,new FinanceAdminRole());
                }
                txtAdminUsrName.setText("");
                txtAdminPwd.setText("");
                txtAdminName.setText("");
                JOptionPane.showMessageDialog(null, "Account created sucessfully");
            } else {
                JOptionPane.showMessageDialog(null, "Please enter unique username", "Warning", JOptionPane.WARNING_MESSAGE);
                txtAdminUsrName.setText("");
            }
        }
    }//GEN-LAST:event_btnAddenterpriseAdminActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adminBackgroundImg;
    private javax.swing.JPanel adminPanelCard;
    private javax.swing.JButton btnAddenterpriseAdmin;
    private javax.swing.JComboBox dropdownEnterprise;
    private javax.swing.JComboBox dropdownNetwork;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblEnterprise;
    private javax.swing.JLabel lblPwd;
    private javax.swing.JLabel lblusrName;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField txtAdminName;
    private javax.swing.JTextField txtAdminPwd;
    private javax.swing.JTextField txtAdminUsrName;
    // End of variables declaration//GEN-END:variables
}
