/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import Business.EcoSystem;
import DB4OUtil.DB4OUtil;
import Employee.Employee;
import User.CoupleUser;
import User.SingleUser;
import com.db4o.ObjectSet;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import ui.BakerPanel.mainPanelBaker;
import ui.FoodAdmin.mainPanelFoodAdmin;
import ui.SystemAdmin.mainPanelSysadmin;
import ui.DecorAdmin.mainPanelDecorAdmin;
import ui.GroomingAdmin.mainPanelGroomingAdmin;
import ui.FinanceAdmin.mainPanelFinanceAdmin;
import ui.User.mainPanelUser;
import ui.CatererPanel.mainPanelCaterer;
import ui.VenueManagerPanel.mainPanelVenueManager;
import ui.DecorationPanel.mainPanelDecoration;
import ui.StylistPanel.mainPanelStylist;
import ui.DesignerPanel.mainPanelDesigner;

import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import ui.SingleUser.mainPanelSingleUser;

/**
 *
 * @author athipathi
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    private EcoSystem system;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    CoupleUser userAccount;
    SingleUser singleuserAccount;
    Employee employeeAccount;
    mainPanelUser userpanel;
    mainPanelSingleUser singleuserpanel;
    public String photoPath;
    public MainJFrame() throws FileNotFoundException {
        initComponents();
        setTitle("The Knot");
        setResizable(false);
        system=dB4OUtil.retrieveSystem();

        System.out.println(system);
        system = dB4OUtil.retrieveSystem();
        loginPanel.setVisible(true);
        upperPanel.setVisible(false);
        mainPanel.setVisible(false);
        registerPanel.setVisible(false);
        registerPanel1.setVisible(false);
        radioButtons();
        loginForm.setBackground(new Color(0,0,0,50));
        registerForm.setBackground(new Color(0,0,0,50));
        registerForm1.setBackground(new Color(0,0,0,50));
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void radioButtons() {
        maleRadio.setActionCommand("Male");
        femaleRadio.setActionCommand("Female");
        maleRadio1.setActionCommand("Male");
        femaleRadio1.setActionCommand("Female");
        genderBtn.add(maleRadio);
        genderBtn.add(femaleRadio);
        genderBtn1.add(maleRadio1);
        genderBtn1.add(femaleRadio1);
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderBtn = new javax.swing.ButtonGroup();
        genderBtn1 = new javax.swing.ButtonGroup();
        loginPanel = new javax.swing.JPanel();
        loginForm = new javax.swing.JPanel();
        txtuserName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPwd = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        btnRegister = new javax.swing.JButton();
        logoImg1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        defaultBackground = new javax.swing.JLabel();
        registerPanel = new javax.swing.JPanel();
        registerForm = new javax.swing.JPanel();
        logoImg2 = new javax.swing.JLabel();
        backImage = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        txtyourName = new javax.swing.JTextField();
        lblName1 = new javax.swing.JLabel();
        txtyourName1 = new javax.swing.JTextField();
        lblName2 = new javax.swing.JLabel();
        txtyourZodiac = new javax.swing.JTextField();
        lblName3 = new javax.swing.JLabel();
        txtyourZodiac1 = new javax.swing.JTextField();
        lblName4 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        lblName5 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        lblName6 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblName7 = new javax.swing.JLabel();
        weddingDateChooser = new com.toedter.calendar.JDateChooser();
        btnRegisterUsr = new javax.swing.JButton();
        heartImg = new javax.swing.JLabel();
        defaultBackground1 = new javax.swing.JLabel();
        upperPanel = new javax.swing.JPanel();
        logoImg = new javax.swing.JLabel();
        logoutImg = new javax.swing.JLabel();
        headerBackgroundImg = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        registerPanel1 = new javax.swing.JPanel();
        registerForm1 = new javax.swing.JPanel();
        logoImg3 = new javax.swing.JLabel();
        backImage1 = new javax.swing.JLabel();
        lblName8 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblName9 = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        lblName10 = new javax.swing.JLabel();
        txtZodiac = new javax.swing.JTextField();
        lblName11 = new javax.swing.JLabel();
        lblName12 = new javax.swing.JLabel();
        txtUserName1 = new javax.swing.JTextField();
        lblName13 = new javax.swing.JLabel();
        txtPassword1 = new javax.swing.JTextField();
        lblName14 = new javax.swing.JLabel();
        btnNextPage = new javax.swing.JButton();
        heartImg1 = new javax.swing.JLabel();
        maleRadio = new javax.swing.JRadioButton();
        femaleRadio = new javax.swing.JRadioButton();
        dropdownHobby = new javax.swing.JComboBox<>();
        lblName16 = new javax.swing.JLabel();
        ProfileImg = new javax.swing.JButton();
        profileImg = new javax.swing.JLabel();
        registerForm2 = new javax.swing.JPanel();
        logoImg4 = new javax.swing.JLabel();
        backImage2 = new javax.swing.JLabel();
        lblName15 = new javax.swing.JLabel();
        lblName17 = new javax.swing.JLabel();
        txtAge1 = new javax.swing.JTextField();
        lblName18 = new javax.swing.JLabel();
        txtpreferedZodiac = new javax.swing.JTextField();
        lblName19 = new javax.swing.JLabel();
        lblName22 = new javax.swing.JLabel();
        btnRegisterUsr2 = new javax.swing.JButton();
        heartImg2 = new javax.swing.JLabel();
        maleRadio1 = new javax.swing.JRadioButton();
        femaleRadio1 = new javax.swing.JRadioButton();
        dropdownHobby1 = new javax.swing.JComboBox<>();
        defaultBackground2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1200, 750));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginPanel.setMinimumSize(new java.awt.Dimension(1300, 800));
        loginPanel.setLayout(null);

        txtuserName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtuserName.setCaretColor(new java.awt.Color(255, 255, 255));

        jLabel1.setText("User Name");

        jLabel2.setText("Password");

        txtPwd.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtPwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPwdActionPerformed(evt);
            }
        });

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        logoImg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo.png"))); // NOI18N

        javax.swing.GroupLayout loginFormLayout = new javax.swing.GroupLayout(loginForm);
        loginForm.setLayout(loginFormLayout);
        loginFormLayout.setHorizontalGroup(
            loginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginFormLayout.createSequentialGroup()
                .addGroup(loginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(loginFormLayout.createSequentialGroup()
                            .addGap(23, 23, 23)
                            .addGroup(loginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(44, 44, 44)
                            .addGroup(loginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtuserName)
                                .addComponent(txtPwd, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginFormLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(49, 49, 49)
                            .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(loginFormLayout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(logoImg1)))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        loginFormLayout.setVerticalGroup(
            loginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginFormLayout.createSequentialGroup()
                .addComponent(logoImg1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(loginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtuserName, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addGap(49, 49, 49)
                .addGroup(loginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPwd, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(loginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );

        loginPanel.add(loginForm);
        loginForm.setBounds(330, 190, 490, 340);

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/couple.png"))); // NOI18N
        jLabel3.setText("Find a Match ");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        loginPanel.add(jLabel3);
        jLabel3.setBounds(650, 530, 180, 40);

        defaultBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/wedding-Background_Image.jpeg"))); // NOI18N
        loginPanel.add(defaultBackground);
        defaultBackground.setBounds(0, 0, 1210, 700);

        getContentPane().add(loginPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, 700));

        registerPanel.setLayout(null);

        logoImg2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo.png"))); // NOI18N

        backImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.png"))); // NOI18N
        backImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backImageMouseClicked(evt);
            }
        });

        lblName.setText("Your Name");

        lblName1.setText("Partner's Name");

        lblName2.setText("Your Zodiac");

        lblName3.setText("Partner's Zodiac ");

        lblName4.setText("User Name");

        lblName5.setText("Password");

        lblName6.setText("Email");

        lblName7.setText("Planned Wedding Date");

        btnRegisterUsr.setText("Create Account");
        btnRegisterUsr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterUsrActionPerformed(evt);
            }
        });

        heartImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/rings.png"))); // NOI18N

        javax.swing.GroupLayout registerFormLayout = new javax.swing.GroupLayout(registerForm);
        registerForm.setLayout(registerFormLayout);
        registerFormLayout.setHorizontalGroup(
            registerFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerFormLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(backImage)
                .addGap(321, 321, 321)
                .addComponent(logoImg2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(registerFormLayout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addGroup(registerFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registerFormLayout.createSequentialGroup()
                        .addGroup(registerFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtyourName, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblName6, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(registerFormLayout.createSequentialGroup()
                        .addGroup(registerFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblName4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblName2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtyourZodiac, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                        .addComponent(heartImg, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)))
                .addGroup(registerFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtyourName1, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                    .addComponent(lblName1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtyourZodiac1, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                    .addComponent(lblName3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                    .addComponent(lblName5, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblName7, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(weddingDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(134, 134, 134))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerFormLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegisterUsr, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(429, 429, 429))
        );
        registerFormLayout.setVerticalGroup(
            registerFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(registerFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(logoImg2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backImage))
                .addGap(39, 39, 39)
                .addGroup(registerFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(registerFormLayout.createSequentialGroup()
                        .addGroup(registerFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, registerFormLayout.createSequentialGroup()
                                .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtyourName, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(registerFormLayout.createSequentialGroup()
                                .addComponent(lblName1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtyourName1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(22, 22, 22)
                        .addGroup(registerFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, registerFormLayout.createSequentialGroup()
                                .addComponent(lblName2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtyourZodiac, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(registerFormLayout.createSequentialGroup()
                                .addComponent(lblName3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtyourZodiac1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(22, 22, 22)
                        .addComponent(lblName4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(registerFormLayout.createSequentialGroup()
                        .addGroup(registerFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblName5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(heartImg, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22)
                .addGroup(registerFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(registerFormLayout.createSequentialGroup()
                        .addComponent(lblName7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(weddingDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(registerFormLayout.createSequentialGroup()
                        .addComponent(lblName6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(btnRegisterUsr, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        weddingDateChooser.setBackground(new Color(0,0,0,0));

        registerPanel.add(registerForm);
        registerForm.setBounds(80, 30, 1040, 580);

        defaultBackground1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/wedding-Background_Image.jpeg"))); // NOI18N
        registerPanel.add(defaultBackground1);
        defaultBackground1.setBounds(0, 0, 1210, 700);

        getContentPane().add(registerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, 700));

        logoImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo.png"))); // NOI18N

        logoutImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout.png"))); // NOI18N
        logoutImg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutImgMouseClicked(evt);
            }
        });

        headerBackgroundImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/wedding-Background_Image.jpeg"))); // NOI18N
        headerBackgroundImg.setSize(new java.awt.Dimension(1210, 66));

        javax.swing.GroupLayout upperPanelLayout = new javax.swing.GroupLayout(upperPanel);
        upperPanel.setLayout(upperPanelLayout);
        upperPanelLayout.setHorizontalGroup(
            upperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(upperPanelLayout.createSequentialGroup()
                .addComponent(logoImg, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 851, Short.MAX_VALUE)
                .addComponent(logoutImg, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(upperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(upperPanelLayout.createSequentialGroup()
                    .addComponent(headerBackgroundImg, javax.swing.GroupLayout.PREFERRED_SIZE, 1209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        upperPanelLayout.setVerticalGroup(
            upperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logoImg, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(logoutImg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(upperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(upperPanelLayout.createSequentialGroup()
                    .addComponent(headerBackgroundImg, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(upperPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, 70));

        mainPanel.setPreferredSize(new java.awt.Dimension(1210, 630));
        mainPanel.setLayout(new java.awt.CardLayout());
        getContentPane().add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1210, 630));

        registerPanel1.setLayout(null);

        logoImg3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo.png"))); // NOI18N

        backImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.png"))); // NOI18N
        backImage1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backImage1MouseClicked(evt);
            }
        });

        lblName8.setText(" Name");

        lblName9.setText("Age");

        lblName10.setText(" Zodiac");

        lblName11.setText("Gender");

        lblName12.setText("User Name");

        lblName13.setText("Password");

        lblName14.setText("Hobby");

        btnNextPage.setText("Fill Preferences");
        btnNextPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextPageActionPerformed(evt);
            }
        });

        heartImg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/heart.png"))); // NOI18N

        maleRadio.setText("Male");

        femaleRadio.setText("Female");

        dropdownHobby.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Clubbing", "Netflix", "Travelling", "Coding", "Reading", "Foodie", "Cooking", "Painting", "Singing", "Dancing" }));

        lblName16.setText("Profile Picture");

        ProfileImg.setText("Upload Image");
        ProfileImg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProfileImgActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout registerForm1Layout = new javax.swing.GroupLayout(registerForm1);
        registerForm1.setLayout(registerForm1Layout);
        registerForm1Layout.setHorizontalGroup(
            registerForm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerForm1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(backImage1)
                .addGap(321, 321, 321)
                .addComponent(logoImg3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(registerForm1Layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addGroup(registerForm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registerForm1Layout.createSequentialGroup()
                        .addGroup(registerForm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblName12, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblName10, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtZodiac, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                        .addComponent(heartImg1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62))
                    .addGroup(registerForm1Layout.createSequentialGroup()
                        .addGroup(registerForm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(registerForm1Layout.createSequentialGroup()
                                .addComponent(lblName11, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(maleRadio)
                                .addGap(30, 30, 30)
                                .addComponent(femaleRadio))
                            .addGroup(registerForm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblName8, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtUserName1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblName13, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(registerForm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registerForm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(registerForm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblName9, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(registerForm1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(lblName14, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(dropdownHobby, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerForm1Layout.createSequentialGroup()
                            .addComponent(lblName16, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ProfileImg)))
                    .addComponent(profileImg, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(134, 134, 134))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerForm1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNextPage, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        registerForm1Layout.setVerticalGroup(
            registerForm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerForm1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(registerForm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(logoImg3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backImage1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(registerForm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(registerForm1Layout.createSequentialGroup()
                        .addGroup(registerForm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, registerForm1Layout.createSequentialGroup()
                                .addComponent(lblName8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(registerForm1Layout.createSequentialGroup()
                                .addComponent(lblName9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(21, 21, 21)
                        .addGroup(registerForm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(registerForm1Layout.createSequentialGroup()
                                .addComponent(lblName10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtZodiac, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)
                                .addComponent(lblName12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtUserName1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(registerForm1Layout.createSequentialGroup()
                                .addComponent(lblName14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dropdownHobby, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(registerForm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblName16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ProfileImg))
                                .addGap(42, 42, 42))))
                    .addGroup(registerForm1Layout.createSequentialGroup()
                        .addComponent(heartImg1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)))
                .addGroup(registerForm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registerForm1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(lblName13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(registerForm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(maleRadio)
                            .addComponent(femaleRadio)
                            .addComponent(lblName11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(98, 98, 98))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerForm1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(profileImg, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(btnNextPage, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))))
        );

        registerPanel1.add(registerForm1);
        registerForm1.setBounds(80, 30, 1040, 580);

        logoImg4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo.png"))); // NOI18N

        backImage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.png"))); // NOI18N
        backImage2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backImage2MouseClicked(evt);
            }
        });

        lblName15.setText("Preferences:");

        lblName17.setText("Age");

        lblName18.setText(" Zodiac");

        lblName19.setText("Gender");

        lblName22.setText("Hobby");

        btnRegisterUsr2.setText("Create Account");
        btnRegisterUsr2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterUsr2ActionPerformed(evt);
            }
        });

        heartImg2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/heart.png"))); // NOI18N

        maleRadio1.setText("Male");

        femaleRadio1.setText("Female");

        dropdownHobby1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Clubbing", "Netflix", "Travelling", "Coding", "Reading", "Foodie", "Cooking", "Painting", "Singing", "Dancing" }));

        javax.swing.GroupLayout registerForm2Layout = new javax.swing.GroupLayout(registerForm2);
        registerForm2.setLayout(registerForm2Layout);
        registerForm2Layout.setHorizontalGroup(
            registerForm2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerForm2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(backImage2)
                .addGap(321, 321, 321)
                .addComponent(logoImg4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(registerForm2Layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addGroup(registerForm2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registerForm2Layout.createSequentialGroup()
                        .addComponent(lblName15, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(registerForm2Layout.createSequentialGroup()
                        .addGroup(registerForm2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(registerForm2Layout.createSequentialGroup()
                                .addGroup(registerForm2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(registerForm2Layout.createSequentialGroup()
                                        .addGroup(registerForm2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblName18, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtpreferedZodiac, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(registerForm2Layout.createSequentialGroup()
                                        .addComponent(lblName19, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(maleRadio1)
                                        .addGap(30, 30, 30)
                                        .addComponent(femaleRadio1)))
                                .addGap(73, 73, 73))
                            .addGroup(registerForm2Layout.createSequentialGroup()
                                .addGroup(registerForm2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtAge1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblName17, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(registerForm2Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(lblName22, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(dropdownHobby1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(heartImg2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91)
                        .addComponent(btnRegisterUsr2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(134, 134, 134))))
        );
        registerForm2Layout.setVerticalGroup(
            registerForm2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerForm2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(registerForm2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(logoImg4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backImage2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(registerForm2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(registerForm2Layout.createSequentialGroup()
                        .addComponent(lblName15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addGroup(registerForm2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(maleRadio1)
                            .addComponent(femaleRadio1)
                            .addComponent(lblName19, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblName18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtpreferedZodiac, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(registerForm2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(registerForm2Layout.createSequentialGroup()
                                .addComponent(lblName17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtAge1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnRegisterUsr2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(heartImg2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(lblName22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(dropdownHobby1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(143, Short.MAX_VALUE))
        );

        //maleRadio1.setBackground(new Color(0,0,0,0));

        registerPanel1.add(registerForm2);
        registerForm2.setBounds(80, 30, 1040, 580);
        registerForm2.setBackground(new Color(0,0,0,50));

        defaultBackground2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/wedding-Background_Image.jpeg"))); // NOI18N
        registerPanel1.add(defaultBackground2);
        defaultBackground2.setBounds(0, 0, 1210, 700);

        getContentPane().add(registerPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, 700));
        registerForm2.setVisible(false);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPwdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPwdActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        mainPanelSysadmin syspanel= new mainPanelSysadmin(system);
        
        
        String username=txtuserName.getText();
        String password=txtPwd.getText();
        if(username.equals("sysadmin")&& password.equals("sysadmin")){
            mainPanel.add("workArea",syspanel);
            loginPanel.setVisible(false);
            upperPanel.setVisible(true);
            mainPanel.setVisible(true);
            clearLogin();
        }
        else{
        userAccount = system.getCoupledirectory().authenticateUser(username, password);
        if(userAccount!=null){
            loginPanel.setVisible(false);
            upperPanel.setVisible(true);
            mainPanel.setVisible(true);
            userpanel = new mainPanelUser(userAccount);
            mainPanel.add("workArea",userpanel);
            clearLogin();
           
        }
        else{
            employeeAccount =system.getEmployeedirectory().authenticateUser(username, password);
             if(employeeAccount!=null){
                loginPanel.setVisible(false);
                upperPanel.setVisible(true);
                mainPanel.setVisible(true);
                mainPanel.add("workArea",employeeAccount.getRole().createWorkArea(system,employeeAccount));
                
                clearLogin();
             }else{
            singleuserAccount = system.getSingleUserlist().authenticateUser(username, password);
            if(singleuserAccount!=null){
            loginPanel.setVisible(false);
            upperPanel.setVisible(true);
            mainPanel.setVisible(true);
            singleuserpanel = new mainPanelSingleUser(system,singleuserAccount);
            mainPanel.add("workArea",singleuserpanel);
            clearLogin();
           
             }
             else{
             JOptionPane.showMessageDialog(null, "No User Found");
             }
             }
        }
        }
        
       
        //syspanel.setSize(1310, 630);
                   
            CardLayout layout = (CardLayout) mainPanel.getLayout();
            layout.next(mainPanel);
    }//GEN-LAST:event_btnLoginActionPerformed

    private void logoutImgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutImgMouseClicked
        try {
            // TODO add your handling code here:
            logout();
        } catch (IOException ex) {
            Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_logoutImgMouseClicked

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
        loginPanel.setVisible(false);
        upperPanel.setVisible(false);
        mainPanel.setVisible(false);
        registerPanel.setVisible(true);
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void backImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backImageMouseClicked
        // TODO add your handling code here:
        loginPanel.setVisible(true);
        upperPanel.setVisible(false);
        mainPanel.setVisible(false);
        registerPanel.setVisible(false);
        registerPanel1.setVisible(false);
    }//GEN-LAST:event_backImageMouseClicked

    private void btnRegisterUsrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterUsrActionPerformed
        // TODO add your handling code here:
        if(validateCoupleUser()){
            if(system.checkIfUserIsUnique(system,txtUserName.getText())){
            CoupleUser user = new CoupleUser(txtyourName.getText(),txtyourName1.getText(),txtyourZodiac.getText(),txtyourZodiac1.getText(),txtUserName.getText(),txtPassword.getText(),txtEmail.getText(),weddingDateChooser.getDate());
            system.getCoupledirectory().createUserAccount(user);
            JOptionPane.showMessageDialog(null, "User Created Successfully");
            userpanel=new mainPanelUser(user);
            mainPanel.add("workArea",userpanel);
            CardLayout layout = (CardLayout) mainPanel.getLayout();
            layout.next(mainPanel);
            loginPanel.setVisible(false);
            upperPanel.setVisible(true);
            mainPanel.setVisible(true);
            registerPanel.setVisible(false);
            registerPanel1.setVisible(false);
            clearRegister();
            }
            else{
                txtUserName.setText("");
                JOptionPane.showMessageDialog(null, "UserName Already Exists!!!");
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Please Enter All Details");
        }
    }//GEN-LAST:event_btnRegisterUsrActionPerformed

    private void backImage1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backImage1MouseClicked
        // TODO add your handling code here:
        loginPanel.setVisible(true);
        upperPanel.setVisible(false);
        mainPanel.setVisible(false);
        registerPanel.setVisible(false);
         registerPanel1.setVisible(false);
    }//GEN-LAST:event_backImage1MouseClicked

    private void btnNextPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextPageActionPerformed
        // TODO add your handling code here:
        registerForm2.setVisible(true);
        registerForm1.setVisible(false);
    }//GEN-LAST:event_btnNextPageActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
         // TODO add your handling code here:
        loginPanel.setVisible(false);
        upperPanel.setVisible(false);
        mainPanel.setVisible(false);
        registerPanel.setVisible(false);
         registerPanel1.setVisible(true);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void backImage2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backImage2MouseClicked
        // TODO add your handling code here:
        registerForm2.setVisible(false);
        registerForm1.setVisible(true);
    }//GEN-LAST:event_backImage2MouseClicked

    private void btnRegisterUsr2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterUsr2ActionPerformed
        // TODO add your handling code here:
        if(validateSingleUser()){
            if(system.checkIfUserIsUnique(system,txtUserName.getText())){
            SingleUser user=new SingleUser(txtName.getText(),genderBtn.getSelection().getActionCommand(),Integer.parseInt(txtAge.getText()),txtZodiac.getText(),txtUserName1.getText(),txtPassword1.getText(),dropdownHobby.getSelectedItem().toString(),photoPath,Integer.parseInt(txtAge1.getText()),genderBtn1.getSelection().getActionCommand(),dropdownHobby1.getSelectedItem().toString(),txtpreferedZodiac.getText());
            system.getSingleUserlist().createUserAccount(txtName.getText(),genderBtn.getSelection().getActionCommand(),Integer.parseInt(txtAge.getText()),txtZodiac.getText(),txtUserName1.getText(),txtPassword1.getText(),dropdownHobby.getSelectedItem().toString(),photoPath,Integer.parseInt(txtAge1.getText()),genderBtn1.getSelection().getActionCommand(),dropdownHobby1.getSelectedItem().toString(),txtpreferedZodiac.getText());
            JOptionPane.showMessageDialog(null, "User Created Successfully");
            singleuserpanel=new mainPanelSingleUser(system,user);
            mainPanel.add("workArea",singleuserpanel);
            CardLayout layout = (CardLayout) mainPanel.getLayout();
            layout.next(mainPanel);
            loginPanel.setVisible(false);
            upperPanel.setVisible(true);
            mainPanel.setVisible(true);
            registerPanel.setVisible(false);
            registerPanel1.setVisible(false);
            clearRegister();
            }
            else{
                txtUserName.setText("");
                JOptionPane.showMessageDialog(null, "UserName Already Exists!!!");
            }

        }
        else{
             JOptionPane.showMessageDialog(null, "Please Enter All details!!!");
        }
    }//GEN-LAST:event_btnRegisterUsr2ActionPerformed

    private void ProfileImgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProfileImgActionPerformed
        JFileChooser file = new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.Images", "jpg", "gif", "png");
        file.addChoosableFileFilter(filter);
        int result = file.showSaveDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = file.getSelectedFile();
            String path = selectedFile.getAbsolutePath();
            photoPath = path;
            profileImg.setIcon(ResizeImage(path));
        } else if (result == JFileChooser.CANCEL_OPTION) {
            System.out.println("No File Select");
        }
    }//GEN-LAST:event_ProfileImgActionPerformed
    public ImageIcon ResizeImage(String ImagePath) {
        ImageIcon MyImage = new ImageIcon(ImagePath);
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(125, 145, Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
    }
    public boolean validateCoupleUser(){
        boolean valid = true;
        if(txtyourName.getText().isEmpty() || txtyourName1.getText().isEmpty()){
            valid=false;
        }
        if(txtyourZodiac.getText().isEmpty() || txtyourZodiac1.getText().isEmpty()){
            valid=false;
        }
        if(txtUserName.getText().isEmpty() || txtPassword.getText().isEmpty()){
            valid=false;
        }
        if(txtEmail.getText().length()<2 || !txtEmail.getText().matches("^(.+)@(\\S+)$")){
            valid=false;
        }
        if(weddingDateChooser.getDate()== null){
        valid= false;
        }
        return valid;
    }
    public boolean validateSingleUser(){
        boolean valid = true;
        boolean radioSelected;
        boolean radioSelected1;
        try {
            radioSelected = genderBtn.getSelection().isSelected();
        } catch (Exception e) {
            radioSelected = false;
        }
        if (!radioSelected) {
            valid = false;
        }
        if(txtName.getText().isEmpty() || txtZodiac.getText().isEmpty()){
            valid=false;
        }
        if(txtUserName1.getText().isEmpty() || txtPassword1.getText().isEmpty()){
            valid=false;
        }
       if (!isInteger(txtAge.getText())) {
            valid = false;
        }
       if (!isInteger(txtAge1.getText())) {
            valid = false;
        }
       try {
            radioSelected1 = genderBtn1.getSelection().isSelected();
        } catch (Exception e) {
            radioSelected1 = false;
        }
        if (!radioSelected1) {
            valid = false;
        }
        if(txtpreferedZodiac.getText().isEmpty()){
            valid=false;
        }
        return valid;
    }
    private boolean isInteger(String txtField) {
        if (txtField.matches("\\d+")) {
            return true;
        } else {
            return false;
        }
    }
    public void logout() throws IOException{
        dB4OUtil.storeSystem(system);
        
        system=dB4OUtil.retrieveSystem();
        

        loginPanel.setVisible(true);
        upperPanel.setVisible(false);
        mainPanel.setVisible(false);
        
    }
    public void clearRegister(){
        txtyourName.setText("");
        txtyourName1.setText("");
        txtyourZodiac.setText("");
        txtyourZodiac1.setText("");
        txtUserName.setText("");
        txtPassword.setText("");
        txtEmail.setText("");
    }
    public void clearLogin(){
        
        txtuserName.setText("");
        txtPwd.setText("");
        
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MainJFrame().setVisible(true);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ProfileImg;
    private javax.swing.JLabel backImage;
    private javax.swing.JLabel backImage1;
    private javax.swing.JLabel backImage2;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnNextPage;
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnRegisterUsr;
    private javax.swing.JButton btnRegisterUsr2;
    private javax.swing.JLabel defaultBackground;
    private javax.swing.JLabel defaultBackground1;
    private javax.swing.JLabel defaultBackground2;
    private javax.swing.JComboBox<String> dropdownHobby;
    private javax.swing.JComboBox<String> dropdownHobby1;
    private javax.swing.JRadioButton femaleRadio;
    private javax.swing.JRadioButton femaleRadio1;
    private javax.swing.ButtonGroup genderBtn;
    private javax.swing.ButtonGroup genderBtn1;
    private javax.swing.JLabel headerBackgroundImg;
    private javax.swing.JLabel heartImg;
    private javax.swing.JLabel heartImg1;
    private javax.swing.JLabel heartImg2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblName1;
    private javax.swing.JLabel lblName10;
    private javax.swing.JLabel lblName11;
    private javax.swing.JLabel lblName12;
    private javax.swing.JLabel lblName13;
    private javax.swing.JLabel lblName14;
    private javax.swing.JLabel lblName15;
    private javax.swing.JLabel lblName16;
    private javax.swing.JLabel lblName17;
    private javax.swing.JLabel lblName18;
    private javax.swing.JLabel lblName19;
    private javax.swing.JLabel lblName2;
    private javax.swing.JLabel lblName22;
    private javax.swing.JLabel lblName3;
    private javax.swing.JLabel lblName4;
    private javax.swing.JLabel lblName5;
    private javax.swing.JLabel lblName6;
    private javax.swing.JLabel lblName7;
    private javax.swing.JLabel lblName8;
    private javax.swing.JLabel lblName9;
    private javax.swing.JPanel loginForm;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JLabel logoImg;
    private javax.swing.JLabel logoImg1;
    private javax.swing.JLabel logoImg2;
    private javax.swing.JLabel logoImg3;
    private javax.swing.JLabel logoImg4;
    private javax.swing.JLabel logoutImg;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JRadioButton maleRadio;
    private javax.swing.JRadioButton maleRadio1;
    private javax.swing.JLabel profileImg;
    private javax.swing.JPanel registerForm;
    private javax.swing.JPanel registerForm1;
    private javax.swing.JPanel registerForm2;
    private javax.swing.JPanel registerPanel;
    private javax.swing.JPanel registerPanel1;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtAge1;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtPassword1;
    private javax.swing.JPasswordField txtPwd;
    private javax.swing.JTextField txtUserName;
    private javax.swing.JTextField txtUserName1;
    private javax.swing.JTextField txtZodiac;
    private javax.swing.JTextField txtpreferedZodiac;
    private javax.swing.JTextField txtuserName;
    private javax.swing.JTextField txtyourName;
    private javax.swing.JTextField txtyourName1;
    private javax.swing.JTextField txtyourZodiac;
    private javax.swing.JTextField txtyourZodiac1;
    private javax.swing.JPanel upperPanel;
    private com.toedter.calendar.JDateChooser weddingDateChooser;
    // End of variables declaration//GEN-END:variables
}
